export const reducerCase = {
  SET_Token: "SET_TOKEN",
  SET_PLAYLISTS: "SET_PLAYLISTS",
  SET_USERINFO: "SET_USERINFO",
  SET_PLAYLIST: "SET_PLAYLIST",
  SET_PLAYING: "SET_PLAYING",
  SET_PLAYER_STATE: "SET_PLAYER_STATE",
  SET_PLAYLIST_ID: "SET_PLAYLIST_ID",
};
